services:
  fq-server:
    build:
      context: server
    ports:
      - 8080:8080
  fq-client:
    build:
      context: client
    ports:
      - 8081:8081
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    command: --quiet
volumes:
  mongodb_data_container:
